import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import Header from "@/components/custom/Header";
import StoreProvider from "./StateProvider";
import { Toaster } from "@/components/ui/toast";
import Refresher from "@/components/custom/Refresher";

const manrope = Manrope({ subsets: ["latin"], variable: "--font-manrope" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${manrope.variable} h-full antialiased`}>
      <StoreProvider>
        <body className="min-h-full flex flex-col">
          <Refresher>
            <Header />
            <main>{children}</main>
            <Toaster />
          </Refresher>
        </body>
      </StoreProvider>
    </html>
  );
}
